function [F_motor,M_motor,rpm_motor_dot] = motor_model(F,M,motor_rpm,params)

% Input parameters
% 
%   F,M: required force and moment
%
%   motor_rpm: current motor RPM
%
%   params: Quadcopter parameters
%
% Output parameters
%
%   F_motor: Actual thrust generated by Quadcopter's Motors
%
%   M_motor: Actual Moment generated by the Quadcopter's Motors
%
%   rpm_motor_dot: Derivative of the RPM
%
%************ MOTOR MODEL ************************

ct = params.thrust_coefficient;
cq = params.moment_scale;
d = params.arm_length;

mat = [ct ct ct ct; 0 d*ct 0 -d*ct; -d*ct 0 d*ct 0; -cq cq -cq cq];

req_fm = [F; M];

w_des_squared = mat\req_fm;
w_des = sqrt(w_des_squared);

vector = mat*((motor_rpm).^2);

F_motor = vector(1);
M_motor = vector(2:4);

rpm_motor_dot = params.motor_constant*(w_des - motor_rpm);

end
